name: Common Python + UV Setup

runs:
  using: "composite"

  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v35
    - name: Restore and save Nix store
      uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}
        gc-max-store-size: 10G
