name: Linter + formatter checks

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v35

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}
          gc-max-store-size: 10G

      - run: nix fmt
